title : Iterum Aerial
tagline: Iterum Aerial
author :
  name : Jan Zheng
  email : contact@janzheng.com
  github : janzheng

markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:title.html
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "notes.txt"]

kramdown:
  input: GFM
  hard_wrap: false

sass:
  sass_dir: _sass
  style: :expanded
  # nested
  # expanded
  # compact
  # compressed
